"""Google Trends collector: independent demand validation.

Why bother when ShopMy already gives click data: ShopMy clicks are generated by
creator audiences. If clicks climb while public search interest is flat, the
movement may be creator-side promotion rather than genuine consumer pull. That
divergence matters to TRACE, because organizing presale demand around a product
that only creators care about is a different bet than one the public is hunting
for. The gap between these two series is a signal in itself.

Caveat: pytrends is an unofficial endpoint and rate-limits aggressively. Terms
are kept few, failures are soft, and results are confidence-tagged `observed`
only when a series actually came back.
"""

WINDOW = "now 7-d"


def collect(terms: list[str], geo: str = "US") -> list[dict]:
    """Return one row per term comparing the last 24h against the prior 6 days."""
    try:
        from pytrends.request import TrendReq
    except ImportError:
        return [{"term": t, "window": WINDOW, "mean_recent": None, "mean_prior": None,
                 "ratio": None, "confidence": "unavailable",
                 "note": "pytrends not installed"} for t in terms]

    rows = []
    for term in terms:
        try:
            p = TrendReq(hl="en-US", tz=300)
            p.build_payload([term], timeframe=WINDOW, geo=geo)
            df = p.interest_over_time()
            if df is None or df.empty:
                raise ValueError("empty series")
            s = df[term]
            s = s[:-1] if len(s) > 1 else s          # drop the partial final bucket
            recent, prior = s.tail(24), s.iloc[:-24] if len(s) > 24 else s
            mr = float(recent.mean())
            mp = float(prior.mean()) if len(prior) else None
            rows.append({
                "term": term, "window": WINDOW,
                "mean_recent": round(mr, 2),
                "mean_prior": round(mp, 2) if mp is not None else None,
                "ratio": round(mr / mp, 3) if mp else None,
                "confidence": "observed",
            })
        except Exception as e:
            rows.append({"term": term, "window": WINDOW, "mean_recent": None,
                         "mean_prior": None, "ratio": None,
                         "confidence": "unavailable", "note": str(e)[:80]})
    return rows
